### ISSUE TITLE
Best tree?

### ISSUE THREAD

**Issue by snacktavish** [SchriderLab/drosophila_phylogeny#2]
Hello! Thanks for posting your data and results. This looks great. I looking for a tree for a downstream analysis incorporating species relationships. Which of your phylogenies you would suggest using?

**Comment by antonysuv** [comment]
Hi there! Sure thing and thank you. So, It depends. If you need a fossil calibrated tree (the branch lengths expressed in Mya) I would use: 
```schemeA.tre``` https://github.com/SchriderLab/drosophila_phylogeny/blob/master/tree/schemeA.tre
this tree has exact same topology as
```iqtree.tre``` https://github.com/SchriderLab/drosophila_phylogeny/blob/master/tree/iqtree.tre
The ```iqtree.tre``` is an ML tree inferred from the supermatrix of all BUSCO orthologs that was subsequently used as a fixed topology in a fossil calibration analyses that generated the ```schemeA.tre``` file.

**Comment by snacktavish** [comment]
Thank you! It was a pretty subjective question- but this is perfect. I’ll go with the dated tree. Thanks for your quick answer and for your accessible data sharing.
